name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Wireguard
        run: |
          sudo apt-get update && sudo apt-get install wireguard openresolv -y
          sudo mkdir -p /etc/wireguard
          
          cat << EOF | sudo tee -a /etc/wireguard/client.conf
          [Interface]
          Address = 10.7.0.2/24
          DNS = 8.8.8.8, 8.8.4.4
          PrivateKey = CHANGE_PRIV_KEY

          [Peer]
          PublicKey = CHANGE_PUB_KEY
          PresharedKey = CHANGE_PRE_KEY
          AllowedIPs = 0.0.0.0/0, ::/0
          Endpoint = CHANGE_ENDPOINT
          PersistentKeepalive = 25
          EOF
          
          sudo sed -i --expression "s@CHANGE_PRIV_KEY@${{ secrets.CHANGE_PRIV_KEY }}@" /etc/wireguard/client.conf
          sudo sed -i --expression "s@CHANGE_PUB_KEY@${{ secrets.CHANGE_PUB_KEY }}@" /etc/wireguard/client.conf
          sudo sed -i --expression "s@CHANGE_PRE_KEY@${{ secrets.CHANGE_PRE_KEY }}@" /etc/wireguard/client.conf
          sudo sed -i --expression "s@CHANGE_ENDPOINT@${{ secrets.CHANGE_ENDPOINT }}@" /etc/wireguard/client.conf
          
          sudo wg-quick up client

          
      # - name: test
      #   run: |
      #     wget -qO - icanhazip.com
      # - name: test2
      #   run: |
      #     curl https://raw.githubusercontent.com/macvk/dnsleaktest/master/dnsleaktest.sh -o dnsleaktest.sh
      #     chmod +x dnsleaktest.sh
      #     ./dnsleaktest.sh
      #- name: Speedtest
      #  run: |
      #    curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
      #    sudo apt-get install speedtest
      #    speedtest --accept-license --accept-gdpr
      - name: Dockerfile
        run: |
          sudo mkdir /dockerfile
          
          cat << EOF | sudo tee -a /dockerfile/Dockerfile
          FROM python:3.9.12-slim-bullseye
          RUN apt-get update -yqq && apt-get install -yqq curl wget git gnupg unzip jq
          CMD wget -qO - icanhazip.com
          EOF
          
          docker build /dockerfile/Dockerfile -t redxlus/get-ip
      - name: Docker compose
        run: |
          sudo mkdir /dockercompose
          
          cat << EOF | sudo tee -a /dockercompose/runner.yml
          version: '3'
          services:
            runner:
              deploy:
                replicas: 1
              image: redxlus/get-ip
              restart: always
          EOF
          
          docker-compose up
          docker ps




