name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Openvpn
        run: |
          sudo apt-get update && sudo apt-get install wireguard -y
          sudo mkdir -p /etc/wireguard/clients
          
      - name: test
        run: |
          dig TXT +short o-o.myaddr.l.google.com @ns1.google.com 


