name: CI matrix
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  example_matrix:
    strategy:
      matrix:
        id: [12, 14, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose
        run: echo ${{ matrix.id }}
        
